Beat-n game with 10 pt limit

## Spud code

In [1]:
using Random
using DataFrames
using CSV
using DelimitedFiles
using Statistics
using Printf
using LinearAlgebra
using Dates

In [2]:
struct Spud
    name::String
    h::Int64
    f::Int64
    l::Int64
    p::Int64
    r::Int64
    s::Int64
    a1::Int64
end

In [3]:
const ability_none = 999
const ability_imitative = 10
const ability_reciprocating = 20
const ability_romantic = 30
const ability_bibliophile = 40
const ability_melodious = 50
const ability_iconoclast = 90
const ability_intoxicating = 100
const ability_otaku = 110
const ability_sincere = 120
const ability_cowardly = 130


ability_name = Dict(
    ability_imitative => "Imitative*",
    ability_reciprocating => "Reciprocating*",
    ability_romantic => "Romantic*",
    ability_bibliophile => "Bibliophile*",
    ability_melodious => "Melodious*",
    ability_iconoclast => "Iconoclast*",
    ability_intoxicating => "Intoxicating*",
    ability_otaku => "Otaku*",
    ability_sincere => "Sincere*",
    ability_cowardly => "Cowardly*",
)

function fx_imitative(a::Spud, b::Spud)
    if b.h > a.h
        a = Spud(a.name, b.h, a.f, a.l, a.p, a.r, a.s, a.a1)
    end
    return [a, b]
end

function fx_reciprocating(a::Spud, b::Spud)
    if b.f > a.f
        a = Spud(a.name, a.h, b.f, a.l, a.p, a.r, a.s, a.a1)
    end
    return [a, b]
end

function fx_romantic(a::Spud, b::Spud)
    if b.p > a.l
        a = Spud(a.name, a.h, a.f, b.p, a.p, a.r, a.s, a.a1)
    end
    return [a, b]
end

function fx_bibliophile(a::Spud, b::Spud)
    if b.r > a.l
        a = Spud(a.name, a.h, a.f, b.r, a.p, a.r, a.s, a.a1)
    end
    return [a, b]
end

function fx_melodious(a::Spud, b::Spud)
    if b.p > b.r && b.p > b.s
        a = Spud(a.name, a.h, a.f, a.r, a.p + 3, a.r, a.s, a.a1)
    end
    return [a, b]
end

function fx_iconoclast(a::Spud, b::Spud)
    v = sum([b.h,b.f,b.l,b.p,b.r,b.s] .== MXV)
    if v >= 3
        aa = [a.h, a.f, a.l, a.p, a.r, a.s]
        aa2 = map(x -> div(x, 4), aa)
        r = aa .+ aa2
        a = Spud(a.name, r[1], r[2], r[3], r[4], r[5], r[6], a.a1)
    end
    return [a, b]
end

function fx_intoxicating(a::Spud, b::Spud)
    b = Spud(b.name, b.h, b.f, b.l, b.p, b.r, b.f, b.a1)
    return [a, b]
end

function fx_otaku(a::Spud, b::Spud)
    b = Spud(b.name, b.h, b.f, b.l, b.p, b.h, b.s, b.a1)
    return [a, b]
end


function fx_sincere(a::Spud, b::Spud)
    b = Spud(b.name, b.h, b.f + 2, b.f + 2, b.p, b.r, b.s, b.a1)
    return [a, b]
end

function fx_cowardly(a::Spud, b::Spud)
    if (a.p < b.p) || (a.r < b.r) || (a.s < b.s)
        a = Spud(a.name, a.h + 2, a.f - 2, a.l, a.p, a.r, a.s, a.a1)
    end
    return [a, b]
end

ability_fx = Dict(
    ability_imitative => fx_imitative,
    ability_reciprocating => fx_reciprocating,
    ability_romantic => fx_romantic,
    ability_bibliophile => fx_bibliophile,
    ability_melodious => fx_melodious,
    ability_iconoclast => fx_iconoclast,
    ability_intoxicating => fx_intoxicating,
    ability_otaku => fx_otaku,
    ability_sincere => fx_sincere,
    ability_cowardly => fx_cowardly,
)

Dict{Int64, Function} with 10 entries:
  50  => fx_melodious
  20  => fx_reciprocating
  110 => fx_otaku
  10  => fx_imitative
  90  => fx_iconoclast
  30  => fx_romantic
  120 => fx_sincere
  130 => fx_cowardly
  40  => fx_bibliophile
  100 => fx_intoxicating

In [4]:
#const MXS = 100
const MXV = 9
const MNV = 1

# function cost(h::Int64, f::Int64, l::Int64, p::Int64, r::Int64, s::Int64)::Int64
#     #return h*(f+l-2*MNV) + f*(p+r+s-3*MNV) + h+f+l+p+r+s-6*MNV
#     return h*(f+l) + f*(p+r+s)
# end

# function cost(a::Spud)::Int64
#     if a.a1 == ability_none
#         return cost(a.h, a.f, a.l, a.p, a.r, a.s)
#     else
#         return cost(a.h, a.f, a.l, a.p, a.r, a.s) + ability_cost[a.a1](a)
#     end
# end

1

In [5]:
function compare_int_list(as::Vector{Int64}, bs::Vector{Int64}, tiebreaker::Int64 = 0)::Int64
    n = min(length(as), length(bs))
    for i in 1:n
        if as[i] != bs[i]
            return sign(as[i] - bs[i])
        end
    end
    return tiebreaker
end

function spud_h_seq(a::Spud)::Vector{Int64}
    return [a.h, a.s, a.r, a.p, a.l, a.f]
end

function spud_f_seq(a::Spud)::Vector{Int64}
    return [a.f, a.s, a.r, a.p, a.l, a.h]
end

function spud_l_seq(a::Spud)::Vector{Int64}
    return [a.l]
end

function spud_p_seq(a::Spud)::Vector{Int64}
    return [a.p, a.l]
end

function spud_r_seq(a::Spud)::Vector{Int64}
    return [a.r, a.f]
end

function spud_s_seq(a::Spud)::Vector{Int64}
    return [a.s, a.h]
end

function spud_utb_seq(a::Spud)::Vector{Int64}
    return [a.a1, a.h, a.f, a.l, a.p, a.r, a.s]
end

function eval_finds(a::Spud, b::Spud, tiebreaker::Int64 = 0)::Int64
    ev = compare_int_list(spud_f_seq(a), spud_h_seq(b), tiebreaker)
    ans = ev
end

function eval_melee(a::Spud, b::Spud, tiebreaker1::Int64 = 0, tiebreaker2::Int64 = 0)::Int64
    comp_p = compare_int_list(spud_p_seq(a), spud_p_seq(b), tiebreaker1)
    comp_r = compare_int_list(spud_r_seq(a), spud_r_seq(b), tiebreaker1)
    comp_s = compare_int_list(spud_s_seq(a), spud_s_seq(b), tiebreaker1)
    ev = 4 * comp_p + 3 * comp_r + 2 * comp_s
    return sign(ev + (1-abs(ev))*tiebreaker2)
end



eval_melee (generic function with 3 methods)

In [6]:


function apply_ability(a::Spud, b::Spud)::Array{Spud}
    if a.a1 == ability_none
        return [a, b]
    else
        return ability_fx[a.a1](a, b)
    end
end


function eval_battle(a::Spud, b::Spud)::Int64
    utb = compare_int_list(spud_utb_seq(a), spud_utb_seq(b), 0) # universal tiebreaker
    if utb == 0
        return 0
    end
    a_ability_first = compare_int_list([a.a1, a.s], [b.a1, b.s], utb)
    if a_ability_first ==1
        if a.a1 != ability_none
            res = apply_ability(a, b)
            a = res[1]
            b = res[2]
        end
        if b.a1 != ability_none
            res = apply_ability(b, a)
            b = res[1]
            a = res[2]
        end
    end
    if a_ability_first == -1
        if b.a1 != ability_none
            res = apply_ability(b, a)
            b = res[1]
            a = res[2]
        end
        if a.a1 != ability_none
            res = apply_ability(a, b)
            a = res[1]
            b = res[2]
        end
    end
    #println(a)
    #println(b)
    a_finds = eval_finds(a, b, utb)==1
    b_finds = eval_finds(b, a, utb)==1
    melee_win = eval_melee(a, b, 0, 0)
    luck_win = compare_int_list([a.l, melee_win], [b.l, -melee_win], 0)
    if melee_win ==1 && luck_win ==1
        return 1
    end
    if melee_win == -1 && luck_win == -1
        return -1
    end
    if a_finds && b_finds
        return melee_win
    end
    if a_finds && !b_finds
        return 1
    end
    if !a_finds && b_finds
        return -1
    end
    if !a_finds && !b_finds
        return luck_win
    end
end

eval_battle (generic function with 1 method)

In [7]:
tab = CSV.read("census_yob2022_names.txt", DataFrame, header = false)
names = tab.Column1
adjectives = CSV.read("adjectives.csv", DataFrame)
nouns = CSV.read("nouns.csv", DataFrame)
jobs = CSV.read("jobs.csv", DataFrame)


const mult_noun = 1
const mult_adj = 2
const mult_job = 3


function random_name_and_stat(ability::Int64 = ability_none)::Spud
    vp = [0, 0, 0, 0, 0, 0]
    #nametype = rand([1,1,1,1,1,2,2,2,3])
    name = ""
    noun = ""
    adj = ""
    noun_i = rand(1:nrow(nouns))
    noun = nouns[noun_i, :noun]
    vp[1] = vp[1] + nouns[noun_i, :H] * mult_noun
    vp[2] = vp[2] + nouns[noun_i, :F] * mult_noun
    vp[3] = vp[3] + nouns[noun_i, :L] * mult_noun
    vp[4] = vp[4] + nouns[noun_i, :P] * mult_noun
    vp[5] = vp[5] + nouns[noun_i, :R] * mult_noun
    vp[6] = vp[6] + nouns[noun_i, :S] * mult_noun
    adj_i = rand(1:nrow(adjectives))
    if ability == ability_none
        adj = adjectives[adj_i, :adjective]
        vp[1] = vp[1] + adjectives[adj_i, :H] * mult_adj
        vp[2] = vp[2] + adjectives[adj_i, :F] * mult_adj
        vp[3] = vp[3] + adjectives[adj_i, :L] * mult_adj
        vp[4] = vp[4] + adjectives[adj_i, :P] * mult_adj
        vp[5] = vp[5] + adjectives[adj_i, :R] * mult_adj
        vp[6] = vp[6] + adjectives[adj_i, :S] * mult_adj
    else
        adj = ability_name[ability]
    end
    job_i = rand(1:nrow(jobs))
    job = jobs[job_i, :job]
    vp[1] = vp[1] + jobs[job_i, :H] * mult_job
    vp[2] = vp[2] + jobs[job_i, :F] * mult_job
    vp[3] = vp[3] + jobs[job_i, :L] * mult_job
    vp[4] = vp[4] + jobs[job_i, :P] * mult_job
    vp[5] = vp[5] + jobs[job_i, :R] * mult_job
    vp[6] = vp[6] + jobs[job_i, :S] * mult_job
    name = string(adj, " ", job, " ", noun)
    Spud(name, vp[1], vp[2], vp[3], vp[4], vp[5], vp[6], ability_none)
end

random_name_and_stat (generic function with 2 methods)

In [8]:
function rand_rename(a::Spud, n_tries::Int = 100)::Spud
    best_score = 0.0
    best_b = random_name_and_stat(a.a1)
    for ii in 1:n_tries
        b = random_name_and_stat(a.a1)
        b_norm = sqrt(b.h^2 + b.f^2 + b.l^2 + b.p^2 + b.r^2 + b.s^2)
        score = (a.h * b.h + a.f * b.f + a.l * b.l + a.p * b.p + a.r * b.r + a.s * b.s)/b_norm
        if score > best_score
            best_score = score
            best_b = b
        end
    end
    return Spud(best_b.name, a.h, a.f, a.l, a.p, a.r, a.s, a.a1)
end

rand_rename (generic function with 2 methods)

In [9]:
function eval_battle_list(a::Spud, bs::Array{Spud})::Int
    score = 0
    for ii in 1:length(bs)
        score = score + eval_battle(a, bs[ii])
    end
    return score
end

function eval_battle_list2(a::Spud, bs::Array{Spud}, w::Vector{Float64})::AbstractFloat
    score = 0.0
    for ii in 1:length(bs)
        score = score + w[ii] * eval_battle(a, bs[ii])
    end
    return score
end

function spuds_to_df(as::Array{Spud})::DataFrame
    names = Array{String}(undef, length(as))
    hs = Array{Int}(undef, length(as))
    fs = Array{Int}(undef, length(as))
    ls = Array{Int}(undef, length(as))
    ps = Array{Int}(undef, length(as))
    rs = Array{Int}(undef, length(as))
    ss = Array{Int}(undef, length(as))
    a1s = Array{Int}(undef, length(as))
    for ii in 1:length(as)
        names[ii] = as[ii].name
        hs[ii] = as[ii].h
        fs[ii] = as[ii].f
        ls[ii] = as[ii].l
        ps[ii] = as[ii].p
        rs[ii] = as[ii].r
        ss[ii] = as[ii].s
        a1s[ii] = as[ii].a1
    end
    df = DataFrame(name = names, h = hs, f = fs, l = ls, p = ps, r = rs, s = ss, a1 = a1s)
    return df
end

function fpart(x::AbstractFloat)::AbstractFloat
  return x - trunc(x)
end

# for legacy dfs without abilities
function df_to_spuds0(df::DataFrame)::Array{Spud}
    n = size(df)[1]
    as = Array{Spud}(undef, n)
    for i in 1:n
        as[i] = Spud(df[i, :name], df[i, :h], df[i, :f], df[i, :l], df[i, :p], df[i, :r], df[i, :s], ability_none)
    end
    return as
end

function df_to_spuds(df::DataFrame)::Array{Spud}
    n = size(df)[1]
    as = Array{Spud}(undef, n)
    for i in 1:n
        as[i] = Spud(df[i, :name], df[i, :h], df[i, :f], df[i, :l], df[i, :p], df[i, :r], df[i, :s], df[i, :a1])
    end
    return as
end



df_to_spuds (generic function with 1 method)

## Get spuds with cost 10 and filter nondominated

In [10]:
function get_library(cost, n_init = 10000)
    ffs = Array{Spud}(undef, n_init)
    ff_i = 0
    hrange = MNV:MXV
    frange = MNV:MXV
    lrange = MNV:MXV
    prange = MNV:MXV
    rrange = MNV:MXV
    srange = MNV:MXV
    for h in hrange
        for f in frange
            for l in lrange
                for p in prange
                    for r in rrange
                        for s in srange
                            if (h+f+l+p+r+s == cost)
                                ff = Spud("", h,f,l,p,r,s,999)
                                ff_i += 1
                                ffs[ff_i] = ff
                            end
                        end
                    end                        
                end                        
            end
        end
    end
    ffs = ffs[1:ff_i]
    return unique(ffs)
end

get_library (generic function with 2 methods)

In [11]:
lib0 = get_library(10)
lib0

126-element Vector{Spud}:
 Spud("", 1, 1, 1, 1, 1, 5, 999)
 Spud("", 1, 1, 1, 1, 2, 4, 999)
 Spud("", 1, 1, 1, 1, 3, 3, 999)
 Spud("", 1, 1, 1, 1, 4, 2, 999)
 Spud("", 1, 1, 1, 1, 5, 1, 999)
 Spud("", 1, 1, 1, 2, 1, 4, 999)
 Spud("", 1, 1, 1, 2, 2, 3, 999)
 Spud("", 1, 1, 1, 2, 3, 2, 999)
 Spud("", 1, 1, 1, 2, 4, 1, 999)
 Spud("", 1, 1, 1, 3, 1, 3, 999)
 Spud("", 1, 1, 1, 3, 2, 2, 999)
 Spud("", 1, 1, 1, 3, 3, 1, 999)
 Spud("", 1, 1, 1, 4, 1, 2, 999)
 ⋮
 Spud("", 3, 1, 3, 1, 1, 1, 999)
 Spud("", 3, 2, 1, 1, 1, 2, 999)
 Spud("", 3, 2, 1, 1, 2, 1, 999)
 Spud("", 3, 2, 1, 2, 1, 1, 999)
 Spud("", 3, 2, 2, 1, 1, 1, 999)
 Spud("", 3, 3, 1, 1, 1, 1, 999)
 Spud("", 4, 1, 1, 1, 1, 2, 999)
 Spud("", 4, 1, 1, 1, 2, 1, 999)
 Spud("", 4, 1, 1, 2, 1, 1, 999)
 Spud("", 4, 1, 2, 1, 1, 1, 999)
 Spud("", 4, 2, 1, 1, 1, 1, 999)
 Spud("", 5, 1, 1, 1, 1, 1, 999)

In [12]:
function get_payoffs(env::Array{Spud})::Array{Int64}
    n_nash = length(env)
    payoffs = Array{Int64}(undef, (n_nash, n_nash))
    for i in 1:n_nash
        for j in 1:n_nash
            payoffs[i, j] = eval_battle(env[i], env[j])
        end
    end
    return payoffs
end

get_payoffs (generic function with 1 method)

In [13]:
function filter_nondominated2(as::Array{Spud})::Array{Spud}
    mat = get_payoffs(as);
    isDominated = zeros(Int64, length(as));
    for i in 1:length(as)
        v = mat[i, :]
        bv = ones(Int64, length(as))
        for j in 1:length(as)
            bv = bv .* (mat[:, j] .>= v[j])
        end
        if sum(bv) > 1
            isDominated[i] = 1
        end
    end
    return as[isDominated .== 0]
end

filter_nondominated2 (generic function with 1 method)

In [14]:
lib=filter_nondominated2(lib0)
for ff in lib
    print(" ")
    print(100000 * ff.h + 10000 * ff.f + 1000 * ff.l + 100 * ff.p + 10 * ff.r + ff.s)
end

 111124 111133 111142 111214 111223 111232 111241 111313 111322 111331 111412 111421 111511 112114 112123 112132 112141 112213 112222 112231 112312 112321 112411 113113 113122 113131 113212 113221 113311 114112 114121 114211 121114 121123 121132 121213 121222 121231 121312 121321 121411 122113 122122 122212 122221 122311 123112 123211 131113 131122 131212 131221 131311 132112 132211 141112 141211 212113 212122 212131 212212 212221 212311 213112 213121 213211 214111 222112 222211 312112 312121 312211 313111 412111

In [15]:
payoffs = get_payoffs(lib)

74×74 Matrix{Int64}:
  0  -1  -1  -1  -1  -1  -1   1  -1  …  -1  -1  -1  -1  -1  -1  -1  -1  -1
  1   0  -1  -1  -1  -1  -1  -1   1     -1  -1  -1  -1  -1  -1  -1  -1  -1
  1   1   0  -1  -1  -1  -1  -1  -1     -1  -1  -1  -1  -1  -1  -1  -1  -1
  1   1   1   0  -1  -1  -1  -1  -1     -1  -1  -1  -1  -1  -1  -1  -1  -1
  1   1   1   1   0  -1  -1  -1  -1     -1  -1  -1  -1  -1  -1  -1  -1  -1
  1   1   1   1   1   0  -1  -1  -1  …  -1  -1  -1  -1  -1  -1  -1  -1  -1
  1   1   1   1   1   1   0  -1  -1     -1  -1  -1  -1  -1  -1  -1  -1  -1
 -1   1   1   1   1   1   1   0  -1     -1  -1  -1  -1  -1  -1  -1  -1  -1
  1  -1   1   1   1   1   1   1   0     -1  -1  -1  -1  -1  -1  -1  -1  -1
  1   1  -1   1   1   1   1   1   1     -1  -1  -1  -1  -1  -1  -1  -1  -1
 -1  -1   1   1  -1   1   1   1   1  …  -1  -1  -1  -1  -1  -1  -1  -1  -1
  1  -1  -1   1   1  -1   1   1   1     -1  -1  -1  -1  -1  -1  -1  -1  -1
 -1  -1  -1   1  -1  -1   1   1  -1     -1  -1  -1  -1  -1  -1  -1  -1  -1
  ⋮ 

## Battle code

In [16]:
mutable struct BattleView
    round::Int64
    score::Int64
    own::Array{Spud}
    obs::Array{Spud}
end

mutable struct AiPlayer
    create::Function
end

In [17]:
function initialize_game()::Array{BattleView}
    bvs = [BattleView(0,0, [], []), BattleView(0,0, [], [])]
    return bvs
end

initialize_game()

2-element Vector{BattleView}:
 BattleView(0, 0, Spud[], Spud[])
 BattleView(0, 0, Spud[], Spud[])

In [18]:
mod(2, 2)

0

In [19]:
lib[end]

Spud("", 4, 1, 2, 1, 1, 1, 999)

In [20]:
function spud_to_str(ff::Spud)::String
    return string(100000 * ff.h + 10000 * ff.f + 1000 * ff.l + 100 * ff.p + 10 * ff.r + ff.s)
end

spud_to_str (generic function with 1 method)

In [21]:
function eval_beat_n(ff::Spud, opps::Array{Spud})::Int64
    flag = true
    count = 0
    while flag && count < length(opps)
        b = opps[end - count]
        if eval_battle(ff, b) == 1
            count += 1
        else
            flag = false
        end
    end
    return count
end

eval_beat_n (generic function with 1 method)

In [22]:
# occurs after spud creation
function play_combat(game::Array{BattleView}, verbose::Bool = false)::Array{BattleView}
    round = game[1].round
    if mod(round, 2)==1
        ff = game[1].own[end]
        opps = game[2].own
    else
        ff = game[2].own[end]
        opps = game[1].own
    end
    count = eval_beat_n(ff, opps)
    if verbose
        print(spud_to_str(ff))
        print(" beats ")
        println([spud_to_str(b) for b in opps[(end-count+1):end]])
    end
    if mod(round, 2)==1
        game[1].score = count
    else
        game[2].score = count
    end
    return game
end

play_combat (generic function with 2 methods)

In [23]:
function play_add_spud(game::Array{BattleView}, player::Int64, ff::Spud, verbose::Bool = false)::Array{BattleView}
    round = game[1].round + 1
    game[1].round = round
    game[2].round = round
    game[player].own = append!(game[player].own, [ff])
    game[3-player].obs = game[player].own
    if verbose
        print("Round ")
        println(round)
        print("Score to match or beat: ")
        println(max(game[1].score, game[2].score))
        print("Player ")
        print(player)
        print(" adds #")
        print(["A", "B"][player])
        print(length(game[player].own))
        print(" ")
        println(spud_to_str(ff))
    end
    return game
end



play_add_spud (generic function with 2 methods)

In [24]:
opps = lib[[5,4,3,2,1]]
ff = lib[3]
opps

5-element Vector{Spud}:
 Spud("", 1, 1, 1, 2, 2, 3, 999)
 Spud("", 1, 1, 1, 2, 1, 4, 999)
 Spud("", 1, 1, 1, 1, 4, 2, 999)
 Spud("", 1, 1, 1, 1, 3, 3, 999)
 Spud("", 1, 1, 1, 1, 2, 4, 999)

In [25]:
ff

Spud("", 1, 1, 1, 1, 4, 2, 999)

In [26]:
team_a = lib[9:11]
team_b = lib[[1,10]]
game = [BattleView(5, 2, team_a, team_b), BattleView(5, 2, team_b, team_a)]

2-element Vector{BattleView}:
 BattleView(5, 2, Spud[Spud("", 1, 1, 1, 3, 2, 2, 999), Spud("", 1, 1, 1, 3, 3, 1, 999), Spud("", 1, 1, 1, 4, 1, 2, 999)], Spud[Spud("", 1, 1, 1, 1, 2, 4, 999), Spud("", 1, 1, 1, 3, 3, 1, 999)])
 BattleView(5, 2, Spud[Spud("", 1, 1, 1, 1, 2, 4, 999), Spud("", 1, 1, 1, 3, 3, 1, 999)], Spud[Spud("", 1, 1, 1, 3, 2, 2, 999), Spud("", 1, 1, 1, 3, 3, 1, 999), Spud("", 1, 1, 1, 4, 1, 2, 999)])

In [27]:
team_a

3-element Vector{Spud}:
 Spud("", 1, 1, 1, 3, 2, 2, 999)
 Spud("", 1, 1, 1, 3, 3, 1, 999)
 Spud("", 1, 1, 1, 4, 1, 2, 999)

In [28]:
team_b

2-element Vector{Spud}:
 Spud("", 1, 1, 1, 1, 2, 4, 999)
 Spud("", 1, 1, 1, 3, 3, 1, 999)

In [29]:
play_combat(game, true)

111412 beats ["111331"]


2-element Vector{BattleView}:
 BattleView(5, 1, Spud[Spud("", 1, 1, 1, 3, 2, 2, 999), Spud("", 1, 1, 1, 3, 3, 1, 999), Spud("", 1, 1, 1, 4, 1, 2, 999)], Spud[Spud("", 1, 1, 1, 1, 2, 4, 999), Spud("", 1, 1, 1, 3, 3, 1, 999)])
 BattleView(5, 2, Spud[Spud("", 1, 1, 1, 1, 2, 4, 999), Spud("", 1, 1, 1, 3, 3, 1, 999)], Spud[Spud("", 1, 1, 1, 3, 2, 2, 999), Spud("", 1, 1, 1, 3, 3, 1, 999), Spud("", 1, 1, 1, 4, 1, 2, 999)])

In [30]:
play_add_spud(game, 2, lib[20], true)

Round 6
Score to match or beat: 2
Player 2 adds #B3 112231


2-element Vector{BattleView}:
 BattleView(6, 1, Spud[Spud("", 1, 1, 1, 3, 2, 2, 999), Spud("", 1, 1, 1, 3, 3, 1, 999), Spud("", 1, 1, 1, 4, 1, 2, 999)], Spud[Spud("", 1, 1, 1, 1, 2, 4, 999), Spud("", 1, 1, 1, 3, 3, 1, 999), Spud("", 1, 1, 2, 2, 3, 1, 999)])
 BattleView(6, 2, Spud[Spud("", 1, 1, 1, 1, 2, 4, 999), Spud("", 1, 1, 1, 3, 3, 1, 999), Spud("", 1, 1, 2, 2, 3, 1, 999)], Spud[Spud("", 1, 1, 1, 3, 2, 2, 999), Spud("", 1, 1, 1, 3, 3, 1, 999), Spud("", 1, 1, 1, 4, 1, 2, 999)])

In [31]:
play_combat(game, true)

112231 beats String[]


2-element Vector{BattleView}:
 BattleView(6, 1, Spud[Spud("", 1, 1, 1, 3, 2, 2, 999), Spud("", 1, 1, 1, 3, 3, 1, 999), Spud("", 1, 1, 1, 4, 1, 2, 999)], Spud[Spud("", 1, 1, 1, 1, 2, 4, 999), Spud("", 1, 1, 1, 3, 3, 1, 999), Spud("", 1, 1, 2, 2, 3, 1, 999)])
 BattleView(6, 0, Spud[Spud("", 1, 1, 1, 1, 2, 4, 999), Spud("", 1, 1, 1, 3, 3, 1, 999), Spud("", 1, 1, 2, 2, 3, 1, 999)], Spud[Spud("", 1, 1, 1, 3, 2, 2, 999), Spud("", 1, 1, 1, 3, 3, 1, 999), Spud("", 1, 1, 1, 4, 1, 2, 999)])

In [32]:
play_add_spud(game, 1, lib[19], true)

Round 7
Score to match or beat: 1
Player 1 adds #A4 112222


2-element Vector{BattleView}:
 BattleView(7, 1, Spud[Spud("", 1, 1, 1, 3, 2, 2, 999), Spud("", 1, 1, 1, 3, 3, 1, 999), Spud("", 1, 1, 1, 4, 1, 2, 999), Spud("", 1, 1, 2, 2, 2, 2, 999)], Spud[Spud("", 1, 1, 1, 1, 2, 4, 999), Spud("", 1, 1, 1, 3, 3, 1, 999), Spud("", 1, 1, 2, 2, 3, 1, 999)])
 BattleView(7, 0, Spud[Spud("", 1, 1, 1, 1, 2, 4, 999), Spud("", 1, 1, 1, 3, 3, 1, 999), Spud("", 1, 1, 2, 2, 3, 1, 999)], Spud[Spud("", 1, 1, 1, 3, 2, 2, 999), Spud("", 1, 1, 1, 3, 3, 1, 999), Spud("", 1, 1, 1, 4, 1, 2, 999), Spud("", 1, 1, 2, 2, 2, 2, 999)])

In [33]:
play_combat(game, true)

112222 beats String[]


2-element Vector{BattleView}:
 BattleView(7, 0, Spud[Spud("", 1, 1, 1, 3, 2, 2, 999), Spud("", 1, 1, 1, 3, 3, 1, 999), Spud("", 1, 1, 1, 4, 1, 2, 999), Spud("", 1, 1, 2, 2, 2, 2, 999)], Spud[Spud("", 1, 1, 1, 1, 2, 4, 999), Spud("", 1, 1, 1, 3, 3, 1, 999), Spud("", 1, 1, 2, 2, 3, 1, 999)])
 BattleView(7, 0, Spud[Spud("", 1, 1, 1, 1, 2, 4, 999), Spud("", 1, 1, 1, 3, 3, 1, 999), Spud("", 1, 1, 2, 2, 3, 1, 999)], Spud[Spud("", 1, 1, 1, 3, 2, 2, 999), Spud("", 1, 1, 1, 3, 3, 1, 999), Spud("", 1, 1, 1, 4, 1, 2, 999), Spud("", 1, 1, 2, 2, 2, 2, 999)])

In [34]:


function play_is_game_over(game::Array{BattleView})::Bool
    round = game[1].round
    if mod(round, 2)==1
        if game[1].score < game[2].score
            return true
        end
    else
        if game[2].score < game[1].score
            return true
        end        
    end
    return false
end

play_is_game_over (generic function with 1 method)

In [35]:
function ai0_create(a::BattleView)::Spud
    return rand(lib)
end

function ai1_create(a::BattleView)::Spud
    ops = a.obs
    ebs = [eval_beat_n(ff, ops) for ff in lib]
    cands = lib[ebs .== maximum(ebs)]
    return rand(cands)
end


ai1_create (generic function with 1 method)

In [36]:
function play_game(players::Array{AiPlayer}, verbose::Bool = true)::Int64
    ai1 = players[1]
    ai2 = players[2]
    ais = players
    game = initialize_game()
    while !play_is_game_over(game)
        # play a round
        round = game[1].round
        if mod(round, 2)==0
            ff = ais[1].create(game[1])
            game = play_add_spud(game, 1, ff, verbose)
        else
            ff = ais[2].create(game[2])
            game = play_add_spud(game, 2, ff, verbose)
        end
        if round > 0
            game = play_combat(game, verbose)
        else
            println("First round: no combat.")
        end
    end
    if verbose
        println("Game history:")
        for i in 1:length(game[1].own)
            print(spud_to_str(game[1].own[i]))
            print(" ")
            if i <= length(game[2].own)
                println(spud_to_str(game[2].own[i]))
            end
        end
    end
    if game[1].score > game[2].score
        return 1
    else
        return -1
    end
end

play_game (generic function with 2 methods)

In [37]:
ai1 = AiPlayer(ai1_create)
ai2 = AiPlayer(ai1_create)
ais = [ai1, ai2]
play_game(ais, true)

Round 1
Score to match or beat: 0
Player 1 adds #A1 213211
First round: no combat.
Round 2
Score to match or beat: 0
Player 2 adds #B1 121114
121114 beats ["213211"]
Round 3
Score to match or beat: 1
Player 1 adds #A2 131212
131212 beats ["121114"]
Round 4
Score to match or beat: 1
Player 2 adds #B2 121321
121321 beats ["213211", "131212"]
Round 5
Score to match or beat: 2
Player 1 adds #A3 121411
121411 beats ["121114", "121321"]
Round 6
Score to match or beat: 2
Player 2 adds #B3 121222
121222 beats ["213211", "131212", "121411"]
Round 7
Score to match or beat: 3
Player 1 adds #A4 312112
312112 beats ["121114", "121321", "121222"]
Round 8
Score to match or beat: 3
Player 2 adds #B4 212221
212221 beats ["131212", "121411", "312112"]
Round 9
Score to match or beat: 3
Player 1 adds #A5 313111
313111 beats ["121114", "121321", "121222", "212221"]
Round 10
Score to match or beat: 4
Player 2 adds #B5 131113
131113 beats ["121411", "312112", "313111"]
Game history:
213211 121114
131212 1213

1