In [1]:
import mip
import numpy as np

In [46]:
from mip.model import Model, MAXIMIZE, MINIMIZE, BINARY, INTEGER, xsum
p = [10, 13, 18, 31,  7, 15]
w = [11, 15, 20, 35, 10, 33]
c = 40.5
n = len(w)
m = Model('knapsack', MAXIMIZE)
x = [m.add_var(var_type=BINARY) for i in range(n)]
m += xsum(p[i]*x[i] for i in range(n) )
m += xsum(w[i]*x[i] for i in range(n) ) <= c
m.optimize()
selected=[i for i in range(n) if x[i].x>=0.99]
print('selected items: {}'.format(selected))

selected items: [1, 2]


In [17]:
x[1].x

1.0

In [2]:
from numpy.random import randint, rand
clusters = randint(0, 10, 20)
clusters

array([3, 9, 1, 0, 1, 8, 2, 0, 0, 3, 0, 0, 7, 7, 1, 8, 4, 7, 8, 0])

In [78]:
npop = 100
nsets = 10
Cmat = (rand(nsets,npop) > rand(nsets, 1)) + 0.0

In [79]:
csizes = np.sum(Cmat, 1)

In [80]:
csizes

array([ 5., 80., 43., 11., 63.,  1., 40., 96., 76.,  5.])

In [149]:
nsub = 30
csizes_scale = (csizes * nsub/npop).astype(int)
csizes_scale

array([ 1, 24, 12,  3, 18,  0, 12, 28, 22,  1])

In [150]:
i = 0
np.nonzero(Cmat[i, ])[0]

array([10, 36, 65, 84, 90])

In [151]:
m = Model('subsample', MINIMIZE)
delt = m.add_var(var_type=INTEGER)
x = [m.add_var(var_type=BINARY) for i in range(npop)]
m += delt
m += delt <= 3
m += xsum( x[i] for i in range(npop) ) <= nsub
for i in range(nsets):
    m += xsum( x[j] for j in np.nonzero(Cmat[i, ])[0] ) + delt >= csizes_scale[i]
    m += xsum( x[j] for j in np.nonzero(Cmat[i, ])[0] ) - delt <= csizes_scale[i]
#m.optimize()

In [161]:
m.num_rows

22

In [152]:
from numpy.random import choice
x0 = np.zeros(npop)
x0[choice(npop, nsub, False)] = 1
x0 = x0.astype(int)
np.dot(Cmat, x0)

array([ 1., 26., 15.,  2., 17.,  0., 13., 29., 23.,  2.])

In [153]:
np.sum(x0)

30

In [154]:
delt0 = np.ceil(np.amax(np.abs(np.dot(Cmat, x0) - csizes_scale))).astype(int)
delt0

3

In [155]:
m.start = [(delt, delt0)] + [(x[i], x0[i]) for i in range(npop)]

In [163]:
m.num_cols, m.num_rows

(101, 22)

In [164]:
m.optimize()

0

In [157]:
delt.x

3.0

In [158]:
np.array([xx.x for xx in x])

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [159]:

m.num_solutions

1