In [1]:
import cvxpy as cp
import numpy as np

In [4]:
from numpy.random import randint, rand
clusters = randint(0, 10, 20)
clusters

array([5, 9, 1, 6, 2, 3, 2, 6, 0, 5, 3, 0, 8, 0, 1, 9, 6, 9, 2, 3])

In [33]:
npop = 100
nsets = 10
Cmat = (rand(nsets,npop) > rand(nsets, 1)) + 0.0

In [34]:
csizes = np.sum(Cmat, 1)

In [35]:
csizes

array([34., 26., 57., 90., 68., 19., 43., 80., 31., 83.])

In [73]:
nsub = 30
csizes_scale = csizes * nsub/npop
x = cp.Variable(npop, boolean=True)
delt = cp.Variable(1, integer=True)

In [74]:
csizes_scale

array([10.2,  7.8, 17.1, 27. , 20.4,  5.7, 12.9, 24. ,  9.3, 24.9])

In [75]:
constr_d_pos = (delt >= 0)
constr_x_sum = (sum(x) <= nsub)
constr_r_1 = (Cmat * x + delt >= csizes_scale)
constr_r_2 = (Cmat * x - delt <= csizes_scale)
objective = cp.Minimize(delt)
prob = cp.Problem(objective, [constr_x_sum])

In [76]:
prob.solve(solver=cp.ECOS_BB)

1.3557680706848647e-11

In [77]:
print("status:", prob.status)
print("optimal value", prob.value)
print("optimal var", x.value, delt.value)

status: optimal
optimal value 1.3557680706848647e-11
optimal var [8.97076769e-13 8.97076769e-13 8.97076769e-13 8.97076769e-13
 8.97076769e-13 8.97076769e-13 8.97076769e-13 8.97076769e-13
 8.97076769e-13 8.97076769e-13 8.97076769e-13 8.97076769e-13
 8.97076769e-13 8.97076769e-13 8.97076769e-13 8.97076769e-13
 8.97076769e-13 8.97076769e-13 8.97076769e-13 8.97076769e-13
 8.97076769e-13 8.97076769e-13 8.97076769e-13 8.97076769e-13
 8.97076769e-13 8.97076769e-13 8.97076769e-13 8.97076769e-13
 8.97076769e-13 8.97076769e-13 8.97076769e-13 8.97076769e-13
 8.97076769e-13 8.97076769e-13 8.97076769e-13 8.97076769e-13
 8.97076769e-13 8.97076769e-13 8.97076769e-13 8.97076769e-13
 8.97076769e-13 8.97076769e-13 8.97076769e-13 8.97076769e-13
 8.97076769e-13 8.97076769e-13 8.97076769e-13 8.97076769e-13
 8.97076769e-13 8.97076769e-13 8.97076769e-13 8.97076769e-13
 8.97076769e-13 8.97076769e-13 8.97076769e-13 8.97076769e-13
 8.97076769e-13 8.97076769e-13 8.97076769e-13 8.97076769e-13
 8.97076769e-13 8.97